/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EventLog */

#ifndef _Included_EventLog
#define _Included_EventLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EventLog
 * Method:    takeLogs
 * Signature: ()[Ljava/util/Properties;
 */
JNIEXPORT jobjectArray JNICALL Java_EventLog_takeLogs
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
